name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username ouily1 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/ouily1/hello-world-ghcr:latest
          docker push ghcr.io/ouily1/hello-world-ghcr:latest
  deploy_to_ovh:
    runs-on: ubuntu-latest
    needs: [build_and_publish]
    steps:
      - name: SSH into OVH VM and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/ouily1/hello-world-ghcr:latest
            docker run -d -p 8080:80 ghcr.io/ouily1/hello-world-ghcr:latest
